apps/api/tenants/urls.py
from django.urls import path

from .views import TenantAPIListView


app_name = "api-tenants"

urlpatterns = [
    path("", TenantAPIListView.as_view()),
]

apps/tenants/urls.py
from django.urls import include
from django.urls import path

from .views import PrivacyView
from .views import TenantHomeView

app_name = "tenants"

urlpatterns = [
    path("", TenantHomeView.as_view(), name="home"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("dashboard/", include("apps.dashboard.tenant.urls", namespace="dashboard")),
    # path("", include("apps.shared.urls", namespace="shared"))
]

config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from .shared_urls import shared_urlpatterns

urlpatterns = [path("", include("apps.tenants.urls", namespace="tenants"))]
urlpatterns += [*shared_urlpatterns]

admin.site.site_header = "Ticketless Tenant Panel"
admin.site.site_title = "Ticketless - Event Management (Tenant)"
admin.site.index_title = "Dashboard Overview (Tenant)"

ticketless/tenants/urls.py
from django.urls import include
from django.urls import path

from .views import PrivacyView
from .views import TenantEventCheckoutView
from .views import TenantEventDetailView
from .views import TenantHomeView
from .views import TenantTicketDownloadTicketView

app_name = "tenants"

urlpatterns = [
    path("", TenantHomeView.as_view(), name="home"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("events/<slug:slug>/", TenantEventDetailView.as_view(), name="event_detail"),
    path(
        "events/<slug:slug>/checkout/",
        TenantEventCheckoutView.as_view(),
        name="event_ticket_checkout",
    ),
    path(
        "events/tickets/download/<order_item_id>/",
        TenantTicketDownloadTicketView.as_view(),
        name="download_ticket_view",
    ),
    path(
        "dashboard/", include("ticketless.dashboard.tenant.urls", namespace="dashboard")
    ),
    path("actions/", include("ticketless.tenants.actions.urls", namespace="actions")),
]

ticketless/tenants/models.py
# Create your models here.

ticketless/dashboard/tenant/forms.py
from django import forms
from django.db.models import Q
from django_select2 import forms as s2forms

from ticketless.tickets.models import Event
from ticketless.users.models import Profile


class EventWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "title__icontains",
    ]


class UserWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "user__email__icontains",
        "user__username__icontains",
    ]


class AssignScanningPermissionForm(forms.Form):
    event = forms.ModelChoiceField(
        queryset=Event.objects.none(),
        empty_label=None,
    )

    users = forms.ModelMultipleChoiceField(queryset=Profile.objects.none())

    def __init__(self, *args, **kwargs):
        self.manager = kwargs.pop("manager")
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["event"].queryset = Event.objects.filter(is_published=True)
        self.fields["users"].queryset = Profile.objects.filter(
            Q(user__is_staff=False) & Q(user__is_superuser=False)
        ).exclude(
            Q(user=self.request.user) | Q(user__email="AnonymousUser") | Q(role="S")
        )

apps/api/tenants/views.py
from django.shortcuts import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from apps.api.tenants.serializers import TenantSelectSerializer
from apps.tenants.models import Client
from apps.tenants.serializers import ClientSerializer
from rest_framework.response import Response


class TenantAPIListView(APIView):
    """
    GET: List all tenants user belongs to
    POST: Select a tenant by schema
    """
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        # Optionally filter tenants the user belongs to
        tenants = Client.objects.all()
        serializer = ClientSerializer(tenants, many=True)
        return Response(serializer.data, status=200)

    def post(self, request, *args, **kwargs):
        # Select a tenant via schema
        serializer = TenantSelectSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        schema_name = serializer.validated_data.get("schema")

        # Fetch tenant safely
        tenant = get_object_or_404(Client, schema_name=schema_name)
        tenant_serializer = ClientSerializer(instance=tenant)
        return Response(tenant_serializer.data, status=200)

apps/core/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.events.forms import EventLaunchRequestUpdateForm
from apps.events.models import EventLaunchRequest
from apps.tenants.models import Client


@method_decorator(login_required, name="dispatch")
class HomeView(TemplateView):
    template_name = "pages/dashboard/pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_requests_pending"] = EventLaunchRequest.objects.filter(
            status="P"
        )
        context["event_requests"] = EventLaunchRequest.objects.all()
        context["clients"] = Client.objects.exclude(schema_name="public")
        context["event_requests_form"] = EventLaunchRequestUpdateForm(
            manager=self.request.user.profile
        )
        return context

apps/dashboard/tenant/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.tenants.permissions import owner_or_manager_required


@method_decorator([login_required, owner_or_manager_required], name="dispatch")
class HomeView(TemplateView):
    template_name = "tenants/dashboard/pages/home.html"

ticketless/core/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from ticketless.customers.models import Client
from ticketless.events.forms import EventLaunchRequestUpdateForm
from ticketless.events.models import EventLaunchRequest


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "pages/dashboard/pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_requests_pending"] = EventLaunchRequest.objects.filter(
            status="P"
        )
        context["event_requests"] = EventLaunchRequest.objects.all()
        context["clients"] = Client.objects.exclude(schema_name="public")
        context["event_requests_form"] = EventLaunchRequestUpdateForm(
            manager=self.request.user.profile
        )
        return context

ticketless/dashboard/tenant/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import View

from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.events.mixins import JsonPermissionMixin
from ticketless.tickets.forms import EventCreationForm


class ProcessEventCreationView(
    LoginRequiredMixin, IsOwnerOrManager, JsonPermissionMixin, View
):
    permission = "tickets.add_event"
    event_create_form = EventCreationForm

    def post(self, request, *args, **kwargs):
        form = self.event_create_form(request.POST, request.FILES)
        if form.is_valid():
            return JsonResponse({"success": True})
        return JsonResponse({"success": False, "errors": form.errors}, status=400)

ticketless/dashboard/tenant/profiles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import TemplateView

from ticketless.dashboard.tenant.forms import AssignScanningPermissionForm
from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.users.models import Profile


class ProfileView(LoginRequiredMixin, IsOwnerOrManager, TemplateView):
    template_name = "tenants/dashboard/profiles/index.html"
    scanning_form_class = AssignScanningPermissionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profiles_requests"] = Profile.objects.filter(
            Q(user__is_staff=False) & Q(user__is_superuser=False)
        ).exclude(Q(user=self.request.user) | Q(user__email="AnonymousUser"))
        context["assign_scanning_permission_form"] = AssignScanningPermissionForm(
            manager=self.request.user, request=self.request
        )
        return context

ticketless/dashboard/tenant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.tickets.forms import EventCreationForm
from ticketless.tickets.models import Event


class HomeView(LoginRequiredMixin, IsOwnerOrManager, TemplateView):
    template_name = "tenants/dashboard/pages/home.html"
    event_create_form = EventCreationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_create_form"] = self.event_create_form()
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


home = HomeView.as_view()

ticketless/tenants/actions/views.py
import base64
import json
from io import BytesIO

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.text import slugify
from django.views.decorators.http import require_POST
# from weasyprint import HTML

from config.settings.base import env
from ticketless.dashboard.tenant.forms import AssignScanningPermissionForm
from ticketless.tenants.mails import send_ticket_email
from ticketless.tenants.tasks import assign_event_scanning_permission
from ticketless.tenants.tasks import create_or_retrieve_ticket_for_order
from ticketless.tenants.tasks import create_ticket_order
from ticketless.tenants.tasks import create_ticket_order_item
from ticketless.tickets.forms import ProcessTicketCheckoutForm
from ticketless.tickets.models import Event
from ticketless.tickets.models import Order
from ticketless.tickets.models import OrderItem
from ticketless.tickets.serializer import OrderItemSerializer
from ticketless.tickets.serializer import OrderSerializer

paystack_public_key = env("PAYSTACK_PUBLIC_KEY")
paystack_private_key = env("PAYSTACK_PRIVATE_KEY")


@require_POST
def initialize_ticket_purchase_view(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)
    form = ProcessTicketCheckoutForm(request.POST, event=event)
    if not form.is_valid():
        return JsonResponse({"errors": form.errors}, status=400, safe=False)
    email = form.cleaned_data.get("email")
    phone = form.cleaned_data.get("phone_number")
    amount = int(form.cleaned_data.get("total_price"))
    with transaction.atomic():
        order = create_ticket_order(
            {
                "email": email,
                "phone": phone,
                "total_amount": amount,
            },
            event_slug=str(event.slug),
        )
        serializer = OrderSerializer(instance=order)

        item_url = reverse(
            "tenants:actions:process_ticket_order_item_view",
            kwargs={
                "order_id": serializer.data["id"],
                "event_slug": event.slug,
            },
        )
        response_data = serializer.data.copy()
        response_data["order_item_process_url"] = item_url
    return JsonResponse(response_data, status=201, safe=False)


@require_POST
def process_ticket_order_item_view(request, order_id, event_slug):
    try:
        data: dict = json.loads(request.body)
    except json.JSONDecodeError as e:
        return JsonResponse({"errors": json.dumps(e)}, status=400, safe=False)
    with transaction.atomic():
        item = create_ticket_order_item(
            {
                "quantity": data.get("quantity"),
                "ticket_type_id": int(data.get("ticket_type")),
                "amount": data.get("total_price"),
                "trxref": data.get("trxref"),
                "transaction": data.get("transaction"),
                "email": data.get("email"),
                "first_name": data.get("first_name"),
                "last_name": data.get("last_name"),
                "phone": data.get("phone_number"),
                "status": data.get("status"),
            },
            order_id=order_id,
            event_slug=event_slug,
        )
        serializer = OrderItemSerializer(instance=item)
        response_data = serializer.data.copy()
        response_data["success_url"] = reverse(
            "tenants:download_ticket_view", kwargs={"order_item_id": int(item.id)}
        )
    return JsonResponse(response_data, status=200)


@require_POST
def delete_order_payment_view(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.delete()
    return JsonResponse({}, status=204, safe=False)


def load_paystack_payment_key(request):
    return JsonResponse({"key": str(paystack_public_key)}, status=200, safe=False)


def download_ticket_view(request, order_item_id):
    # item = get_object_or_404(OrderItem, id=order_item_id)
    # ticket = create_or_retrieve_ticket_for_order(order_item_id)
    # qr_image_base64 = ""
    # if ticket.qr_code:
    #     with ticket.qr_code.open("rb") as f:
    #         qr_image_base64 = base64.b64encode(f.read()).decode("utf-8")
    # html_string = render_to_string(
    #     "tenants/tickets/ticket_template.html",
    #     {"order_item": item, "ticket": ticket, "qr_image_base64": qr_image_base64},
    # )

    # pdf_file = BytesIO()
    # HTML(string=html_string).write_pdf(pdf_file)
    # pdf_file.seek(0)
    # pdf_data = pdf_file.read()

    # filename = f"ticket-{slugify(item.ticket_type.event.title)}.pdf"
    # if not ticket.sent_mail:
    #     send_ticket_email(item, pdf_data, ticket, filename)
    # response = HttpResponse(pdf_data, content_type="application/pdf")
    # response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return HttpResponse("Ticket download is currently disabled.", content_type="text/plain")


@login_required
@require_POST
def assign_scanning_permission(request):
    form = AssignScanningPermissionForm(
        request.POST, manager=request.user, request=request
    )
    if not form.is_valid():
        return JsonResponse({"errors": form.errors}, safe=False, status=400)
    event = form.cleaned_data.get("event")
    assignee = form.cleaned_data.get("users")
    assign_event_scanning_permission(event, assignee, "scan_tickets")
    return JsonResponse({})

ticketless/tenants/utils/views.py
from django.http import HttpResponseForbidden
from django.http import HttpResponseNotFound
from django.http import HttpResponseServerError
from django.shortcuts import render


def error_403(request, exception=None):
    return HttpResponseForbidden(
        render(request, "tenants/errors/403.html", {"message": str(exception)})
    )


def error_404(request, exception=None):
    return HttpResponseNotFound(render(request, "tenants/errors/404.html"))


def error_500(request):
    return HttpResponseServerError(render(request, "tenants/errors/500.html"))

ticketless/tenants/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from ticketless.tickets.forms import ProcessTicketCheckoutForm
from ticketless.tickets.models import Event
from ticketless.tickets.models import OrderItem


class TenantHomeView(TemplateView):
    template_name = "tenants/pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


class TenantEventDetailView(TemplateView):
    template_name = "tenants/pages/event_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event"] = get_object_or_404(Event, slug=self.kwargs.get("slug"))
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


class TenantEventCheckoutView(TemplateView):
    template_name = "tenants/pages/event_ticket_checkout.html"
    ticket_checkout_form_class = ProcessTicketCheckoutForm

    def _get_event(self):
        return get_object_or_404(Event, slug=self.kwargs.get("slug"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event"] = self._get_event()
        context["ticket_purchase_form"] = self.ticket_checkout_form_class(
            event=self._get_event()
        )
        return context


class TenantTicketDownloadTicketView(TemplateView):
    template_name = "tenants/pages/event_ticket_download.html"

    def _get_order_item(self):
        return get_object_or_404(OrderItem, id=self.kwargs.get("order_item_id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order_item"] = self._get_order_item()
        return context


class PrivacyView(TemplateView):
    template_name = "tenants/pages/privacy.html"

templates/components/header/dashboard/base.html
{% load webpack_static from webpack_loader %}

<header class="header">
  <div class="header-inner">
    <nav class="navbar navbar-expand-lg bg-barren barren-head navbar fixed-top justify-content-sm-start pt-0 pb-0 ps-lg-0 pe-2">
      <div class="container-fluid ps-0">
        <button type="button" id="toggleMenu" class="toggle_menu">
          <i class="ti ti-menu-2"></i>
        </button>
        <button id="collapse_menu" class="collapse_menu me-4">
          <i class="ti ti-menu-2 collapse_menu--icon"></i>
          <span class="collapse_menu--label"></span>
        </button>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
          <span class="close-btn" style="width: 40px"><i class="ti ti-menu-2" style="width: 100%"></i></span>
        </button>
        <a class="navbar-brand order-1 order-lg-0 ml-lg-0 ml-2 me-auto"
           href="{% url 'home' %}">
          <div class="res-main-logo">
            <img src="{% webpack_static 'images/logos/ticketless-icon.png' %}" alt="" />
          </div>
          <div class="main-logo" id="logo">
            <img src="{% webpack_static 'images/logos/ticketless.png' %}" alt="" />
            <img class="logo-inverse"
                 src="{% webpack_static 'images/logos/dark-logo.svg' %}"
                 alt="" />
          </div>
        </a>
        <div class="offcanvas offcanvas-start"
             tabindex="-1"
             id="offcanvasNavbar"
             aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header d-flex d-md-none align-items-center justify-content-between">
            <div class="offcanvas-logo" id="offcanvasNavbarLabel">
              <img src="{% webpack_static 'images/logos/ticketless-icon.png' %}" alt="" />
            </div>
            <button type="button"
                    class="close-btn"
                    data-bs-dismiss="offcanvas"
                    aria-label="Close">
              <i class="ti ti-x"></i>
            </button>
          </div>
          <div class="offcanvas-body">
            <div class="offcanvas-top-area">
              <div class="create-bg">
                <a href="" class="offcanvas-create-btn">
                  <i class="ti ti-calendar-clock"></i>
                  <span>Create Event</span>
                </a>
              </div>
            </div>
            <ul class="navbar-nav justify-content-end grow pe_5">
              <li class="nav-item">
                <a class="nav-link" role="button"><i class="ti ti-arrow-autofit-right me-2"></i>My Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" role="button"><i class="ti ti-compass me-2"></i>Explore Events</a>
              </li>
            </ul>
          </div>
          <div class="offcanvas-footer">
            <div class="offcanvas-social">
              <h5>Follow Us</h5>
              <ul class="social-links">
                <li>
                  <a href="#" class="social-link"><i class="fas fa-facebook"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="right-header order-2">
          <ul class="p-0 m-0">
            <li class="me-1">
              <div class="night_mode_switch__btn">
                <div id="night-mode" class="ti ti-sun"></div>
              </div>
            </li>
            <li class="right-header__login__modal--btn">
              <div class="profile__login">
                <div class="ti ti-user"></div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="overlay"></div>
  </div>
</header>

templates/components/header/dashboard/tenant.html
{% load webpack_static from webpack_loader %}

<header class="header">
  <div class="header-inner">
    <nav class="navbar navbar-expand-lg bg-barren barren-head navbar fixed-top justify-content-sm-start pt-0 pb-0 ps-lg-0 pe-2">
      <div class="container-fluid ps-0">
        <button type="button" id="toggleMenu" class="toggle_menu">
          <i class="ti ti-menu-2"></i>
        </button>
        <button id="collapse_menu" class="collapse_menu me-4">
          <i class="ti ti-menu-2 collapse_menu--icon"></i>
          <span class="collapse_menu--label"></span>
        </button>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
          <span class="close-btn" style="width: 40px"><i class="ti ti-menu-2" style="width: 100%"></i></span>
        </button>
        <a class="navbar-brand order-1 order-lg-0 ml-lg-0 ml-2 me-auto"
           href="{% url 'tenants:home' %}">
          <div class="res-main-logo">
            <img src="{% webpack_static 'images/logos/ticketless-icon.png' %}" alt="" />
          </div>
          <div class="main-logo" id="logo">
            <img src="{% webpack_static 'images/logos/ticketless.png' %}" alt="" />
            <img class="logo-inverse"
                 src="{% webpack_static 'images/logos/ticketless.png' %}"
                 alt="" />
          </div>
        </a>
        <div class="offcanvas offcanvas-start"
             tabindex="-1"
             id="offcanvasNavbar"
             aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header d-flex d-md-none align-items-center justify-content-between">
            <div class="offcanvas-logo" id="offcanvasNavbarLabel">
              <img src="{% webpack_static 'images/logos/ticketless-icon.png' %}" alt="" />
            </div>
            <button type="button"
                    class="close-btn"
                    data-bs-dismiss="offcanvas"
                    aria-label="Close">
              <i class="ti ti-x"></i>
            </button>
          </div>
          <div class="offcanvas-body">
            <div class="offcanvas-top-area">
              <div class="create-bg">
                <a href="" class="offcanvas-create-btn">
                  <i class="ti ti-calendar-clock"></i>
                  <span>Create Event</span>
                </a>
              </div>
            </div>
            <ul class="navbar-nav justify-content-end grow pe_5">
              <li class="nav-item">
                <a class="nav-link" role="button"><i class="ti ti-arrow-autofit-right me-2"></i>My Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" role="button"><i class="ti ti-compass me-2"></i>Explore xxx Events</a>
              </li>
            </ul>
          </div>
          <div class="offcanvas-footer">
            <div class="offcanvas-social">
              <h5>Follow Us</h5>
              <ul class="social-links">
                <li>
                  <a href="#" class="social-link"><i class="fas fa-facebook"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="right-header order-2">
          <ul class="p-0 m-0">
            <li class="me-1">
              <div class="night_mode_switch__btn">
                <div id="night-mode" class="ti ti-sun"></div>
              </div>
            </li>
            <li class="right-header__login__modal--btn">
              <a {% if request.user|is_owner_or_manager_filter %} href="{% url 'tenants:dashboard:profiles:profile_view' %}" {% else %} role="button" {% endif %}
                 class="profile__login">
                <div class="ti ti-user"></div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="overlay"></div>
  </div>
</header>