apps/api/tenants/urls.py
from django.urls import path

from .views import TenantAPIListView


app_name = "api-tenants"

urlpatterns = [
    path("", TenantAPIListView.as_view()),
]

apps/tenants/urls.py
from django.urls import include
from django.urls import path

from .views import PrivacyView
from .views import TenantHomeView

app_name = "tenants"

urlpatterns = [
    path("", TenantHomeView.as_view(), name="home"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("dashboard/", include("apps.dashboard.tenant.urls", namespace="dashboard")),
    # path("", include("apps.shared.urls", namespace="shared"))
]

config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from .shared_urls import shared_urlpatterns

urlpatterns = [path("", include("apps.tenants.urls", namespace="tenants"))]
urlpatterns += [*shared_urlpatterns]

admin.site.site_header = "Ticketless Tenant Panel"
admin.site.site_title = "Ticketless - Event Management (Tenant)"
admin.site.index_title = "Dashboard Overview (Tenant)"

ticketless/tenants/urls.py
from django.urls import include
from django.urls import path

from .views import PrivacyView
from .views import TenantEventCheckoutView
from .views import TenantEventDetailView
from .views import TenantHomeView
from .views import TenantTicketDownloadTicketView

app_name = "tenants"

urlpatterns = [
    path("", TenantHomeView.as_view(), name="home"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("events/<slug:slug>/", TenantEventDetailView.as_view(), name="event_detail"),
    path(
        "events/<slug:slug>/checkout/",
        TenantEventCheckoutView.as_view(),
        name="event_ticket_checkout",
    ),
    path(
        "events/tickets/download/<order_item_id>/",
        TenantTicketDownloadTicketView.as_view(),
        name="download_ticket_view",
    ),
    path(
        "dashboard/", include("ticketless.dashboard.tenant.urls", namespace="dashboard")
    ),
    path("actions/", include("ticketless.tenants.actions.urls", namespace="actions")),
]

apps/tenants/models.py
from django.conf import settings
from django.db import models
from django_tenants.models import DomainMixin
from django_tenants.models import TenantMixin
from django_tenants.postgresql_backend.base import _check_schema_name


class Client(TenantMixin):
    name = models.CharField(max_length=100)
    schema_name = models.CharField(
        max_length=63,
        unique=True,
        db_index=True,
        validators=[_check_schema_name],
        help_text="This will act as the subdomain. fidel in fidel.ticket.io",
    )
    created_on = models.DateField(auto_now_add=True)
    description = models.TextField(blank=True)
    auto_create_schema = True
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="managed_tenants",
        help_text="User responsible for managing this tenant."
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="owned_tenants",
        help_text="User who owns this tenant."
    )

    def primary_domain(self):
        return Domain.objects.filter(tenant=self, is_primary=True).first()


class Domain(DomainMixin):
    domain = models.CharField(
        max_length=253,
        unique=True,
        db_index=True,
        help_text=(
            "This include the schema_name and the base domain. i.e fidel.ticket.io",
        ),
    )

ticketless/tenants/models.py
# Create your models here.

ticketless/dashboard/tenant/forms.py
from django import forms
from django.db.models import Q
from django_select2 import forms as s2forms

from ticketless.tickets.models import Event
from ticketless.users.models import Profile


class EventWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "title__icontains",
    ]


class UserWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "user__email__icontains",
        "user__username__icontains",
    ]


class AssignScanningPermissionForm(forms.Form):
    event = forms.ModelChoiceField(
        queryset=Event.objects.none(),
        empty_label=None,
    )

    users = forms.ModelMultipleChoiceField(queryset=Profile.objects.none())

    def __init__(self, *args, **kwargs):
        self.manager = kwargs.pop("manager")
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["event"].queryset = Event.objects.filter(is_published=True)
        self.fields["users"].queryset = Profile.objects.filter(
            Q(user__is_staff=False) & Q(user__is_superuser=False)
        ).exclude(
            Q(user=self.request.user) | Q(user__email="AnonymousUser") | Q(role="S")
        )

apps/api/tenants/views.py
from django.shortcuts import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from apps.api.tenants.serializers import TenantSelectSerializer
from apps.tenants.models import Client
from apps.tenants.serializers import ClientSerializer
from rest_framework.response import Response


class TenantAPIListView(APIView):
    """
    GET: List all tenants user belongs to
    POST: Select a tenant by schema
    """
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        # Optionally filter tenants the user belongs to
        tenants = Client.objects.all()
        serializer = ClientSerializer(tenants, many=True)
        return Response(serializer.data, status=200)

    def post(self, request, *args, **kwargs):
        # Select a tenant via schema
        serializer = TenantSelectSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        schema_name = serializer.validated_data.get("schema")

        # Fetch tenant safely
        tenant = get_object_or_404(Client, schema_name=schema_name)
        tenant_serializer = ClientSerializer(instance=tenant)
        return Response(tenant_serializer.data, status=200)

apps/dashboard/tenant/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.tenants.permissions import owner_or_manager_required


@method_decorator([login_required, owner_or_manager_required], name="dispatch")
class HomeView(TemplateView):
    template_name = "tenants/dashboard/pages/home.html"

ticketless/dashboard/tenant/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import View

from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.events.mixins import JsonPermissionMixin
from ticketless.tickets.forms import EventCreationForm


class ProcessEventCreationView(
    LoginRequiredMixin, IsOwnerOrManager, JsonPermissionMixin, View
):
    permission = "tickets.add_event"
    event_create_form = EventCreationForm

    def post(self, request, *args, **kwargs):
        form = self.event_create_form(request.POST, request.FILES)
        if form.is_valid():
            return JsonResponse({"success": True})
        return JsonResponse({"success": False, "errors": form.errors}, status=400)

ticketless/dashboard/tenant/profiles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import TemplateView

from ticketless.dashboard.tenant.forms import AssignScanningPermissionForm
from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.users.models import Profile


class ProfileView(LoginRequiredMixin, IsOwnerOrManager, TemplateView):
    template_name = "tenants/dashboard/profiles/index.html"
    scanning_form_class = AssignScanningPermissionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profiles_requests"] = Profile.objects.filter(
            Q(user__is_staff=False) & Q(user__is_superuser=False)
        ).exclude(Q(user=self.request.user) | Q(user__email="AnonymousUser"))
        context["assign_scanning_permission_form"] = AssignScanningPermissionForm(
            manager=self.request.user, request=self.request
        )
        return context

ticketless/dashboard/tenant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from ticketless.dashboard.tenant.permissions import IsOwnerOrManager
from ticketless.tickets.forms import EventCreationForm
from ticketless.tickets.models import Event


class HomeView(LoginRequiredMixin, IsOwnerOrManager, TemplateView):
    template_name = "tenants/dashboard/pages/home.html"
    event_create_form = EventCreationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_create_form"] = self.event_create_form()
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


home = HomeView.as_view()

ticketless/tenants/actions/views.py
import base64
import json
from io import BytesIO

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.text import slugify
from django.views.decorators.http import require_POST
# from weasyprint import HTML

from config.settings.base import env
from ticketless.dashboard.tenant.forms import AssignScanningPermissionForm
from ticketless.tenants.mails import send_ticket_email
from ticketless.tenants.tasks import assign_event_scanning_permission
from ticketless.tenants.tasks import create_or_retrieve_ticket_for_order
from ticketless.tenants.tasks import create_ticket_order
from ticketless.tenants.tasks import create_ticket_order_item
from ticketless.tickets.forms import ProcessTicketCheckoutForm
from ticketless.tickets.models import Event
from ticketless.tickets.models import Order
from ticketless.tickets.models import OrderItem
from ticketless.tickets.serializer import OrderItemSerializer
from ticketless.tickets.serializer import OrderSerializer

paystack_public_key = env("PAYSTACK_PUBLIC_KEY")
paystack_private_key = env("PAYSTACK_PRIVATE_KEY")


@require_POST
def initialize_ticket_purchase_view(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)
    form = ProcessTicketCheckoutForm(request.POST, event=event)
    if not form.is_valid():
        return JsonResponse({"errors": form.errors}, status=400, safe=False)
    email = form.cleaned_data.get("email")
    phone = form.cleaned_data.get("phone_number")
    amount = int(form.cleaned_data.get("total_price"))
    with transaction.atomic():
        order = create_ticket_order(
            {
                "email": email,
                "phone": phone,
                "total_amount": amount,
            },
            event_slug=str(event.slug),
        )
        serializer = OrderSerializer(instance=order)

        item_url = reverse(
            "tenants:actions:process_ticket_order_item_view",
            kwargs={
                "order_id": serializer.data["id"],
                "event_slug": event.slug,
            },
        )
        response_data = serializer.data.copy()
        response_data["order_item_process_url"] = item_url
    return JsonResponse(response_data, status=201, safe=False)


@require_POST
def process_ticket_order_item_view(request, order_id, event_slug):
    try:
        data: dict = json.loads(request.body)
    except json.JSONDecodeError as e:
        return JsonResponse({"errors": json.dumps(e)}, status=400, safe=False)
    with transaction.atomic():
        item = create_ticket_order_item(
            {
                "quantity": data.get("quantity"),
                "ticket_type_id": int(data.get("ticket_type")),
                "amount": data.get("total_price"),
                "trxref": data.get("trxref"),
                "transaction": data.get("transaction"),
                "email": data.get("email"),
                "first_name": data.get("first_name"),
                "last_name": data.get("last_name"),
                "phone": data.get("phone_number"),
                "status": data.get("status"),
            },
            order_id=order_id,
            event_slug=event_slug,
        )
        serializer = OrderItemSerializer(instance=item)
        response_data = serializer.data.copy()
        response_data["success_url"] = reverse(
            "tenants:download_ticket_view", kwargs={"order_item_id": int(item.id)}
        )
    return JsonResponse(response_data, status=200)


@require_POST
def delete_order_payment_view(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.delete()
    return JsonResponse({}, status=204, safe=False)


def load_paystack_payment_key(request):
    return JsonResponse({"key": str(paystack_public_key)}, status=200, safe=False)


def download_ticket_view(request, order_item_id):
    # item = get_object_or_404(OrderItem, id=order_item_id)
    # ticket = create_or_retrieve_ticket_for_order(order_item_id)
    # qr_image_base64 = ""
    # if ticket.qr_code:
    #     with ticket.qr_code.open("rb") as f:
    #         qr_image_base64 = base64.b64encode(f.read()).decode("utf-8")
    # html_string = render_to_string(
    #     "tenants/tickets/ticket_template.html",
    #     {"order_item": item, "ticket": ticket, "qr_image_base64": qr_image_base64},
    # )

    # pdf_file = BytesIO()
    # HTML(string=html_string).write_pdf(pdf_file)
    # pdf_file.seek(0)
    # pdf_data = pdf_file.read()

    # filename = f"ticket-{slugify(item.ticket_type.event.title)}.pdf"
    # if not ticket.sent_mail:
    #     send_ticket_email(item, pdf_data, ticket, filename)
    # response = HttpResponse(pdf_data, content_type="application/pdf")
    # response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return HttpResponse("Ticket download is currently disabled.", content_type="text/plain")


@login_required
@require_POST
def assign_scanning_permission(request):
    form = AssignScanningPermissionForm(
        request.POST, manager=request.user, request=request
    )
    if not form.is_valid():
        return JsonResponse({"errors": form.errors}, safe=False, status=400)
    event = form.cleaned_data.get("event")
    assignee = form.cleaned_data.get("users")
    assign_event_scanning_permission(event, assignee, "scan_tickets")
    return JsonResponse({})

ticketless/tenants/utils/views.py
from django.http import HttpResponseForbidden
from django.http import HttpResponseNotFound
from django.http import HttpResponseServerError
from django.shortcuts import render


def error_403(request, exception=None):
    return HttpResponseForbidden(
        render(request, "tenants/errors/403.html", {"message": str(exception)})
    )


def error_404(request, exception=None):
    return HttpResponseNotFound(render(request, "tenants/errors/404.html"))


def error_500(request):
    return HttpResponseServerError(render(request, "tenants/errors/500.html"))

ticketless/tenants/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from ticketless.tickets.forms import ProcessTicketCheckoutForm
from ticketless.tickets.models import Event
from ticketless.tickets.models import OrderItem


class TenantHomeView(TemplateView):
    template_name = "tenants/pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


class TenantEventDetailView(TemplateView):
    template_name = "tenants/pages/event_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event"] = get_object_or_404(Event, slug=self.kwargs.get("slug"))
        context["events"] = Event.objects.all().order_by("-created_at")
        return context


class TenantEventCheckoutView(TemplateView):
    template_name = "tenants/pages/event_ticket_checkout.html"
    ticket_checkout_form_class = ProcessTicketCheckoutForm

    def _get_event(self):
        return get_object_or_404(Event, slug=self.kwargs.get("slug"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event"] = self._get_event()
        context["ticket_purchase_form"] = self.ticket_checkout_form_class(
            event=self._get_event()
        )
        return context


class TenantTicketDownloadTicketView(TemplateView):
    template_name = "tenants/pages/event_ticket_download.html"

    def _get_order_item(self):
        return get_object_or_404(OrderItem, id=self.kwargs.get("order_item_id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order_item"] = self._get_order_item()
        return context


class PrivacyView(TemplateView):
    template_name = "tenants/pages/privacy.html"

templates/tenants/pages/event_detail.html
{% extends 'tenants/base.html' %}

{% load webpack_static from webpack_loader %}

{% block title %}{{ block.super }} | {{ event.title }}{% endblock %}
{% block content %}
  <div class="event-dt-block p-80">
    <div class="container">
      <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12">
          <div class="event-top-dts">
            <div class="event-top-date">
              <span class="event-month">{{ event.start_at|date:'M' }}</span>
              <span class="event-date">{{ event.start_at|date:'d' }}</span>
            </div>
            <div class="event-top-dt">
              <h3 class="event-main-title">
                {{ event.title }} {{ event.start_at|date:'l F j, Y' }} at {{ event.start_at|date:'gA' }}
              </h3>
              <div class="event-top-info-status">
                <span class="event-type-name"><i class="fa-solid fa-location-dot"></i>Venue Event</span>
                <span class="event-type-name details-hr">Starts on <span class="ev-event-date">{{ event.start_at|date:'D, M d, Y g:i A' }}</span></span>
                <span class="event-type-name details-hr">2h</span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-8 col-lg-7 col-md-12">
          <div class="main-event-dt">
            <div class="event-img">
              <img src="{% if event.cover %} {{ event.cover.url }} {% else %} {% webpack_static 'images/events/placeholder.jpg' %} {% endif %}"
                   alt="{{ event.title }}"
                   style="width: 65%;
                          height:50%" />
            </div>
            <div class="share-save-btns dropdown">
              <button class="sv-btn me-2">
                <i class="fa-regular fa-bookmark me-2"></i>Save
              </button>
              <button class="sv-btn" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-share-nodes me-2"></i>Share
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="#"><i class="fa-brands fa-facebook me-3"></i>Facebook</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="fa-brands fa-twitter me-3"></i>Twitter</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="fa-brands fa-linkedin-in me-3"></i>LinkedIn</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="fa-regular fa-envelope me-3"></i>Email</a>
                </li>
              </ul>
            </div>
            <div class="main-event-content">
              <h4>About This Event</h4>
              <p>{{ event.short_description|safe }}</p>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-lg-5 col-md-12">
          <div class="main-card event-right-dt">
            <div class="bp-title d-flex align-items-center justify-content-between">
              <h4>Event Details</h4>
              <span class="event-price me-3">
                Available tickets
                {% if not event.is_expired %}<strong>( {{ event.capacity|default:'0' }} )</strong>{% endif %}
              </span>
            </div>
            <div class="time-left">
              <div class="countdown"
                   data-start-at="{{ event.start_at|date:'Y-m-d H:i:s' }}">
                <div class="countdown-item">
                  <span id="day"></span> Days
                </div>
                <div class="countdown-item">
                  <span id="hour"></span> Hours
                </div>
                <div class="countdown-item">
                  <span id="minute"></span> Minutes
                </div>
                <div class="countdown-item">
                  <span id="second"></span> Seconds
                </div>
              </div>
            </div>
            <div class="event-dt-right-group mt-5">
              <div class="event-dt-right-icon">
                <i class="fa-solid fa-circle-user"></i>
              </div>
              <div class="event-dt-right-content">
                <h4>Organized by</h4>
                <h5>The {{ request.tenant.owner }}</h5>
                <a href="#">View Profile</a>
              </div>
            </div>
            <div class="event-dt-right-group">
              <div class="event-dt-right-icon">
                <i class="fa-solid fa-calendar-day"></i>
              </div>
              <div class="event-dt-right-content">
                <h4>Date and Time</h4>
                <h5>{{ event.start_at|date:'D, M d, Y g:i A' }}</h5>
                <div class="add-to-calendar">
                  <a href="#"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false"><i class="fa-regular fa-calendar-days me-3"></i>Add to Calendar</a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="#"><i class="fa-brands fa-windows me-3"></i>Outlook</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#"><i class="fa-brands fa-apple me-3"></i>Apple</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#"><i class="fa-brands fa-google me-3"></i>Google</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#"><i class="fa-brands fa-yahoo me-3"></i>Yahoo</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="event-dt-right-group">
              <div class="event-dt-right-icon">
                <i class="fa-solid fa-location-dot"></i>
              </div>
              <div class="event-dt-right-content">
                <h4>Location</h4>
                <h5 class="mb-0">{{ event.venue_name }} | {{ event.venue_address }}</h5>
                <a href="#"><i class="fa-solid fa-location-dot me-2"></i>View Map</a>
              </div>
            </div>
            <div class="select-tickets-block"></div>
            <div class="booking-btn">
              {% if event.capacity > 0 and not event.is_expired %}
                <!-- Tickets still available -->
                <a href="{% url 'tenants:event_ticket_checkout' event.slug %}"
                   class="main-btn btn-hover w-100">Purchase Ticket</a>
              {% else %}
                <!-- Sold out -->
                <a role="button"
                   class="main-btn btn-hover w-100 disabled opacity-50 cursor-not-allowed">Sold Out</a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-xl-12 col-lg-12 col-md-12">
          <div class="more-events">
            <div class="main-title position-relative">
              <h3>More Events</h3>
            </div>
            <!-- Swiper Container -->
            <div class="swiper moreEvents-slider">
              <div class="swiper-wrapper">
                {% for item in events %}
                  <!-- Slide {{forloop.counter}} -->
                  <div class="swiper-slide">
                    <div class="main-card mt-4">
                      <div class="event-thumbnail">
                        <a href="{{ item.get_absolute_url }}" class="thumbnail-img">
                          <img src="{% if item.cover %} {{ item.cover.url }} {% else %} {% webpack_static 'images/events/placeholder.jpg' %} {% endif %}"
                               alt="{{ item.title }}" />
                        </a>
                        <span class="bookmark-icon d-flex align-items-center justify-content-between"><i class="fa-regular fa-bookmark"></i></span>
                      </div>
                      <div class="event-content">
                        <a href="{{ item.get_absolute_url }}" class="event-title mb-1">{{ item.title }}</a>
                        <div class="duration-price-remaining">{{ item.short_description|truncatewords:15 }}</div>
                      </div>
                      <div class="event-footer">
                        <div class="event-timing">
                          <div class="publish-date">
                            <span>
                              <i class="fa-solid fa-calendar-day me-2"></i>
                              {{ item.start_at|date:'d M' }}
                            </span>
                            <span class="dot"><i class="fa-solid fa-circle"></i></span>
                            <span>{{ item.start_at|date:'D, g.i A' }}</span>
                          </div>
                          <span class="publish-time"><i class="fa-solid fa-clock me-2"></i>1h</span>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
                <!-- Add more swiper-slide blocks here -->
              </div>
              <!-- If you want navigation -->
              <div class="swiper-button-next"></div>
              <div class="swiper-button-prev"></div>
              <!-- If you want pagination -->
              <div class="swiper-pagination"></div>
            </div>
            <!-- End Swiper -->
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}{% endblock %}

templates/tenants/pages/event_ticket_checkout_cancelled.html
{% extends 'tenants/base.html' %}

{% load webpack_static from webpack_loader %}

{% block title %}{{ block.super }} | {{ event.title }}{% endblock %}
{% block content %}{% endblock %}

templates/tenants/pages/event_ticket_checkout_confirmed.html
{% extends 'tenants/base.html' %}

{% load webpack_static from webpack_loader %}

{% block title %}{{ block.super }} | {{ event.title }}{% endblock %}
{% block content %}{% endblock %}

templates/tenants/pages/event_ticket_download.html
{% extends 'tenants/base.html' %}

{% load webpack_static from webpack_loader %}

{% block title %}{{ block.super }} | {{ event.title }}{% endblock %}
{% block content %}
  <div class="event-dt-block p-80">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-7 col-md-10">
          <div class="booking-confirmed-content">
            <div class="main-card">
              <div class="booking-confirmed-top text-center p_30">
                <div class="booking-confirmed-img mt-4">
                  <img src="{% webpack_static 'images/events/confirmed.png' %}"
                       alt="{{ order_item.ticket_type.event.title }}" />
                </div>
                <h4>Ticket Purchase Successful</h4>
                <p class="ps-lg-4 pe-lg-4">
                  Your ticket has been successfully purchased.
                  <br />
                  The details of your booking are shown below.
                </p>
              </div>
              <div class="booking-confirmed-bottom">
                <div class="booking-confirmed-bottom-bg p_30">
                  <div class="event-order-dt">
                    <div class="event-thumbnail-img">
                      <img src=" {% if order_item.ticket_type.event.cover %} {{ order_item.ticket_type.event.cover.url }} {% else %} {% webpack_static 'images/events/placeholder.jpg' %} {% endif %} "
                           alt="{{ order_item.ticket_type.event.title }}" />
                    </div>
                    <div class="event-order-dt-content">
                      <h5>{{ order_item.ticket_type.event.title|title }}</h5>
                      <span>{{ order_item.ticket_type.event.start_at|date:'D, M d, Y — g:i A' }} • Duration: {{ order_item.ticket_type.event.duration_str }}</span>
                      <div class="buyer-name">{{ order_item.meta.first_name|title }} {{ order_item.meta.last_name|title }}</div>
                      <div class="booking-total-tickets">
                        <i class="fa-solid fa-ticket rotate-icon"></i>
                        <span class="booking-count-tickets mx-2">{{ order_item.quantity }}</span> Ticket{{ order_item.quantity|pluralize }}
                      </div>
                      <div class="booking-total-grand">
                        Total: <span class="currency"
       data-amount="{{ order_item.order.total_amount }}"
       data-currency="{{ order_item.order.currency }}">{{ order_item.order.total_amount }}</span>
                      </div>
                    </div>
                  </div>
                  <a role="button"
                     id="download-ticket"
                     data-href="{% url 'tenants:actions:ticket_download_view' order_item.id %}"
                     class="main-btn btn-hover h_50 w-100 mt-5">
                    <i class="fa-solid fa-ticket rotate-icon me-3"></i>
                    Download Ticket
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}{% endblock %}